time stamp

# P set point
float32 kp_lon_set
float32 kp_lim_set
float32 kp_lat_set
float32 kp_ang_set

# I set point
float32 ki_lon_set
float32 ki_lim_set
float32 ki_lat_set
float32 ki_ang_set

# D set point
float32 kd_lon_set
float32 kd_lim_set
float32 kd_lat_set
float32 kd_ang_set

# D input set point
float32 kd_lon_input_set
float32 kd_lat_input_set
float32 kd_ang_input_set

# errors
float32 lon_err
float32 lat_err
float32 ang_err
float32 real_ang_err

# speeds
float32 ang_speed
float32 lin_speed
float32 speed_limit